// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7RdqLIT9JiQNNPrS1Ba1KSCX9r8J_Tps',
    appId: '1:933945179471:web:093ffa07cf639e177b193a',
    messagingSenderId: '933945179471',
    projectId: 'winter-spotify',
    authDomain: 'winter-spotify.firebaseapp.com',
    storageBucket: 'winter-spotify.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtESqOa7q7ysMN2A0pD4AiTWAh4-o-WEE',
    appId: '1:933945179471:android:94500da3673eb6727b193a',
    messagingSenderId: '933945179471',
    projectId: 'winter-spotify',
    storageBucket: 'winter-spotify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRw7d215lhzTAD012Z2qptiTfTDvt5vo',
    appId: '1:933945179471:ios:cef37422e009c0d47b193a',
    messagingSenderId: '933945179471',
    projectId: 'winter-spotify',
    storageBucket: 'winter-spotify.appspot.com',
    androidClientId: '933945179471-ognd6999ngdpibl2vb1lvkqnn629m2oo.apps.googleusercontent.com',
    iosClientId: '933945179471-uvsqnbpabirm0s6u3suuqa6rvg4uet06.apps.googleusercontent.com',
    iosBundleId: 'com.winter.music',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRw7d215lhzTAD012Z2qptiTfTDvt5vo',
    appId: '1:933945179471:ios:c7bcc5a5894d07387b193a',
    messagingSenderId: '933945179471',
    projectId: 'winter-spotify',
    storageBucket: 'winter-spotify.appspot.com',
    androidClientId: '933945179471-ognd6999ngdpibl2vb1lvkqnn629m2oo.apps.googleusercontent.com',
    iosClientId: '933945179471-v4srjsgbb2q0q5ad7qrcg73o7jjf8hem.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCleanArchitectureSpotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7RdqLIT9JiQNNPrS1Ba1KSCX9r8J_Tps',
    appId: '1:933945179471:web:14f13e320b291f637b193a',
    messagingSenderId: '933945179471',
    projectId: 'winter-spotify',
    authDomain: 'winter-spotify.firebaseapp.com',
    storageBucket: 'winter-spotify.appspot.com',
  );

}